mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),

]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    url(r'^signup/$',views.signup,name='signup'),
    url(r'^signedin/$',views.signedin,name='signedin'),

    url(r'^login/$',views.login,name='login'),
    url(r'^loggedin/$',views.loggedin,name='loggedin'),

    url(r'^loggedout/$',views.loggedout,name='loggedout'),

    url(r'^imageview/$',views.imageview,name='imageview'),
    url(r'^loadui/$',views.loadui,name='loadui'),

    url(r'^comments/$',views.comments,name='comments'),
    url(r'^getcomments/$',views.getcomments,name='getcomments'),
    url(r'^password-reset/$',views.password_reset,name='password_reset')


]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    def __str__(self):
        return self.question_text
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        now =timezone.now()
        return  now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    def __str__(self):
        return self.choice_text
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


class Comments(models.Model):
    author=models.CharField(max_length=20)
    comment_text=models.CharField(max_length=100)
    

polls/forms.py
from django import forms
from .models import Question,Comments
import collections
import datetime
from django.contrib import auth
from django.contrib.auth.models import User
class DetailForm(forms.Form):
    def __init__(self,q_id,*args,**kwargs):
        super(DetailForm,self).__init__(*args,**kwargs)
        self.question=Question.objects.get(pk=q_id)
        self.fields['choice_field'] = forms.ChoiceField(label='' ,
                                                        widget=forms.RadioSelect , 
                                                        choices=self.func())

    def func(self):
        choice_list_of_tuples=[]
        choices=self.question.choice_set.all()
        for index,data in enumerate(choices):
            choice_list_of_tuples.append((index+1,data.choice_text))
        return tuple(choice_list_of_tuples)    

class SignupForm(forms.Form):
    fullName=forms.CharField(label="Username" , max_length=20)
    password=forms.CharField(label="Password" , max_length=14)
    dateOfBirth=forms.DateField(label="Date of Birth")
    email_id=forms.EmailField(label='email_id')

    def person_save(self):
        user=User.objects.create_user(username=self.cleaned_data['fullName'],
                                      password=self.cleaned_data['password'],
                                      date_joined=self.cleaned_data['dateOfBirth'],
                                      email=self.cleaned_data['email_id'])
        user.save()
        return user

class LoginForm(forms.Form):
    user_name=forms.CharField(label="Your name",max_length=20)
    password=forms.CharField(label="Password",max_length=14)

    def person_validate(self):
        user=auth.authenticate(username=self.cleaned_data['user_name'],
                               password=self.cleaned_data['password'])
        if user is not None and user.is_active:
            return user
        return False     



class CommentForm(forms.Form):
    author=forms.CharField(label="Author_name", max_length=20)
    comment_text=forms.CharField(label="Comment",max_length=100)

    def store_comment(self):
        comment=Comments(author=self.cleaned_data['author'],
                        comment_text=self.cleaned_data['comment_text'])
        print("saved")
        comment.save()
        return comment

class PasswordResetForm(forms.Form):
    email_id=forms.EmailField(label='email_id')

        
    

polls/views.py
from django.http import HttpResponseRedirect, HttpResponse,JsonResponse,HttpRequest
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from .models import Question,Choice,Comments
from django.utils import timezone
from .forms import DetailForm,SignupForm,LoginForm,CommentForm,PasswordResetForm
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from mysite.tasks import sendmail

@login_required
def index(request):
    co=Choice.objects.all()
    valid_question_list=[]
    final_list=[]
    valid_questions_by_time=Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:]
    for c in co:
        if  c.question not in valid_question_list:
            valid_question_list.append(c.question)
    length_of_valid_question_list=len(valid_question_list) 
    for question in valid_questions_by_time:
        if question in valid_question_list:
            final_list.append(question)
    latest_question_list = final_list
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

@login_required
def detail(request, question_id):
    form=DetailForm(question_id,request.POST)
    question = get_object_or_404(Question.objects.filter(pub_date__lte=timezone.now()), pk=question_id)
    return render(request, 'polls/detail.html', {'question': question,'form':form})

@login_required
def results(request, question_id):
    question = get_object_or_404(Question.objects.filter(pub_date__lte=timezone.now()), pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        if request.method=='POST':
            form=DetailForm(question_id,request.POST)
            if form.is_valid():
                print(form.cleaned_data['choice_field'])
                choice_id=form.cleaned_data['choice_field']  
        selected_choice = question.choice_set.get(pk=choice_id)
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a valid choice.",
            'form':form
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def signup(request):
    form=SignupForm()
    return render(request,'polls/signup.html',{'form':form})


def signedin(request):
    if request.method=='POST':
        form=SignupForm(request.POST)
        if form.is_valid():
            person=form.person_save()
            url=reverse('polls:login')
            return JsonResponse({'success':url})
        jsonerror=form.errors
        return JsonResponse({'failiure':jsonerror})

def login(request):
    form=LoginForm()

    return render(request,'polls/login.html',{'form':form})

def loggedin(request):
    if request.method=='POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            user=form.person_validate()
            if user is not False:
                auth.login(request, user)
                url=reverse('polls:index')
                return JsonResponse({'success':url})
            else:
                return JsonResponse({'invalid data':'Invalid username or password'})
        jsonerror=form.errors
        return JsonResponse({'failiure':jsonerror})

@login_required
def loggedout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('polls:signup'))

def imageview(request):
    data={'1':'http://media.caranddriver.com/images/media/51/25-cars-worth-waiting-for-lp-ford-gt-photo-658253-s-original.jpg',
          '2':'http://media.caranddriver.com/images/media/51/25-cars-worth-waiting-for-lp-mclaren-p14-photo-658259-s-original.jpg'}
    return JsonResponse(data)

def loadui(request):
    result=add.delay(4,4)
    return render(request,'polls/imageview.html')

@csrf_exempt
def getcomments(request):
    comment_list=[]
    for comment in Comments.objects.all():
        comment_list.append({'id':comment.id,
                            'author':comment.author,
                            'text':comment.comment_text})
        print(comment.id)
    return JsonResponse({'stuff':comment_list})

@csrf_exempt
def comments(request):
    if request.method=='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.store_comment()
            print("successful save")
            return JsonResponse({'success!':'yay'})
    else:
        return render(request,'polls/comments.html')

@csrf_exempt
def password_reset(request):
    if request.method=='POST':
        print("a")
        form=PasswordResetForm(request.POST)
        if form.is_valid():
            print("b")
            sendmail.delay(form.cleaned_data['email_id'])
            return render(request,'polls/login.html')
    else:
        return render(request,'polls/password-reset.html')

polls/templates/polls/comments.html
<!-- index.html -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>React Tutorial</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.2.0/react.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.2.0/react-dom.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.34/browser.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/remarkable/1.6.2/remarkable.min.js"></script>
  </head>
  <body>
    <div id="content"></div>
    <script type="text/babel">
        var CommentPage=React.createClass({
          getInitialState: function() {
            return {author: '', text: '',data:[]};
          },
          handleAuthorChange: function(e) {
            this.setState({author: e.target.value});
          },
          handleTextChange: function(e) {
            this.setState({text: e.target.value});
          },

          componentDidMount: function() {
            $.ajax({
              url: '/polls/getcomments/',
              cache: false,
              success: function(data) {
                this.setState({data: data['stuff']});
              }.bind(this),
              error: function(xhr, status, err) {
                console.error(this.props.url, status, err.toString());
              }.bind(this)
            });
          },

          handleSubmit: function(e) {
            e.preventDefault();
            this.state.data.push({author:this.state.author,text:this.state.text,id:Date.now()});
            $.ajax({
              url:'/polls/comments/',
              type:'POST',
              data:{'author':this.state.author,'comment_text':this.state.text},
              success: function(data) {
                console.log(data);
              },
            })
            var author = this.state.author.trim();
            var text = this.state.text.trim();
            this.setState({author: '',text:''});
          },
          render:function() {
            return (
              <div className="commentpage">
              <form onSubmit={this.handleSubmit}>
                <input
                  name='author'
                  type="text"
                  placeholder="name"
                  value={this.state.author}
                  onChange={this.handleAuthorChange}
                />
                <input
                  name='comment_text'
                  type="text"
                  placeholder="comment"
                  value={this.state.text}
                  onChange={this.handleTextChange}
                />
                <input type="submit" value="Post"  /> 
              </form>
              <CommentList data={this.state.data}/>
              </div>
            );   
          },
        });

        var CommentList = React.createClass({
          render: function() {
            var commentnode= this.props.data.map(function(comment) {
              return (
                  <div className='commentl' key={comment.id}>
                  <Comment author={comment.author}  >
                  { comment.text}
                  </Comment>
                  </div>
                );
            });
            return (
              <div className="commentlist">
              {commentnode}
              </div>
            );
            
          },
        });

        var Comment= React.createClass({
          render: function() {
            return (
              <div className='comment'>
                <h2>{this.props.author}</h2>
                <p>{this.props.children}</p>
                </div>

            );
          },
        });
        ReactDOM.render(
          <CommentPage />,
          document.getElementById('content')
        );
    </script>
  </body>
</html>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:loggedout' %}">
    <input class=" waves-effect waves-light btn" style="float: right;" type="submit" value="Logout">
</form>
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{{form}}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/imageview.html
{% load staticfiles %}
<html>
    <body>
        <p>load!</p>
        <div id='images'></div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.2.0/react.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.2.0/react-dom.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.34/browser.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
        <script type="text/babel">

            var Imageview = React.createClass({
                  getInitialState: function() {
                    return {data: []};
                  },
                componentDidMount: function() {
                    $.ajax({
                        url:'/polls/imageview',
                        success: function(data) {
                            this.setState({data:data[randumnum()]});
                            console.log(data);
                        }.bind(this),
                    });
                },
                render: function() {
                    return (
                        <div className="imgview"> 
                            <Myimage data= {this.state.data} />
                        </div>
                    );
                },
                });
            function randumnum() {
                return 1+Math.floor(2*Math.random());
            }

            var Myimage = React.createClass({
                render: function() {
                    return (
                        <div className="myimage"><img src={this.props.data}/> </div>
                    );
                },

            });
            ReactDOM.render(
                <Imageview />,
                document.getElementById('images')
            ); 

        </script>
    </body>
</html>

polls/templates/polls/index.html
{% load staticfiles %}
<link rel="stylesheet" type=text/css href="{% static 'polls/css/materialize.css' %}" />
<form action="{% url 'polls:loggedout' %}">
    <input class=" waves-effect waves-light btn" style="float: right;" type="submit" value="Logout">
</form>
<br>
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}" />
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}
        </a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/loggedout.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
<p>You successfully logged out!</p>
</body>
</html>

polls/templates/polls/login.html
{% load staticfiles %}
<html>
    <body>
        <link rel="stylesheet" type=text/css href="{% static 'polls/css/materialize.css' %}" />
        <div id="wrong_user"></div>
        <div class="row">
            <form class="col s12" id="myform" >
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s6 ">
                        <input type="text" id="username" name="user_name"  class="validate " > 
                        <label for="username"> Username </label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6 ">
                        <input type="text" id="password" name="password" class="validate ">
                        <label for="password" >Password</label>
                    </div>
                </div>
                <div class="center-align">
                    <button class="btn waves-effect waves-light" id="mybutton" type="submit" name="action">Log in             
                    </button>
                </div>
            </form>
        </div>
        <script src="{%static 'polls/js/jquery-3.0.js' %}"></script>
        <script src="{% static 'polls/js/materialize.js' %}"></script>
        <script src="{% static 'polls/js/loginjquery.js' %}"></script>
    </body>
</html>

polls/templates/polls/password-reset.html
{% load staticfiles %}
<html>
    <body>
        <link rel="stylesheet" type=text/css href="{% static 'polls/css/materialize.css' %}" />
        <form method='POST'>
            <div class="row">
                <div class="input-field col s6 ">
                    <input type="email" id="email_id" name="email_id"  class="validate " > 
                    <label for="email_id"> Email id </label>
                </div>
            </div>
             <button class="btn waves-effect waves-light" id="mybutton" type="submit" name="action"> Submit             
                    </button>
        </form>
        <script src="{%static 'polls/js/jquery-3.0.js' %}"></script>
        <script src="{% static 'polls/js/materialize.js' %}"></script>
    </body>
</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<form action="{% url 'polls:loggedout' %}">
    <input class=" waves-effect waves-light btn" style="float: right;" type="submit" value="Logout">
</form>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/signup.html
{% load staticfiles %}
<html>
    <body>
        <link rel="stylesheet" type=text/css href="{% static 'polls/css/materialize.css' %}" />
        <div class="row">
        <form action="{% url 'polls:password_reset' %}">
            <button class=" waves-effect waves-light btn" style="float: right;" type="submit" value="Login">Forgot Password
            </button>
            <br><br>
        </form>
            <form class="col s12" id="myform" >
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s6 ">
                        <input type="text" id="name" name="fullName"  class="validate " > 
                        <label for="name"> Username </label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6 ">
                        <input type="text" id="password" name="password" class="validate ">
                        <label for="password" > Password</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6 ">
                        <input  type="email" id="email_id" name="email_id"  class="validate "> 
                        <label for="email_id" >Email id</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6 ">
                        <input  type="date" id="DOB" name="dateOfBirth"  class="validate "> 
                        <label for="DOB" ></label>
                    </div>              
                </div>
                <br>    
                <div class="center-align">
                    <button class="btn waves-effect waves-light" id="mybutton" type="submit" name="action">Sign Up             
                    </button>
                    <br><br>

                </div>
            </form>
        </div>
        <form action="{% url 'polls:login' %}">
            <button class=" waves-effect waves-light btn" style="float: center;" type="submit" value="Login">Login
            </button>
        </form>
        <script src="{%static 'polls/js/jquery-3.0.js' %}"></script>
        <script src="{% static 'polls/js/materialize.js' %}"></script>
        <script src="{% static 'polls/js/signupjquery.js' %}"></script>
    </body>
</html>